<?php
/**
 * Created by PhpStorm.
 * User: longbob
 * Date: 2018/7/18
 * Time: 下午10:38
 */

namespace ext\lib\framework;


use ext\service\TcpClientService;
use Hhxsv5\LaravelS\LaravelS;

class MyLaravelS extends LaravelS
{

    protected $tcpClientService;

    public function __construct(array $svrConf, array $laravelConf , TcpClientService $tcpClientService)
    {
        parent::__construct($svrConf, $laravelConf);
        $this->tcpClientService = $tcpClientService;
    }




    public function onWorkerStart(\swoole_http_server $server, $workerId)
    {
        parent::onWorkerStart($server, $workerId); // TODO: Change the autogenerated stub
        if ( $workerId == 0){
            // worker 0 start any one
            go(function(){
               $this->tcpClientService->getRpcClient()->startBeat();
            });
        }
    }


}